CREATE TABLE IF NOT EXISTS Users (
    idUsers SERIAL PRIMARY KEY,
    Login VARCHAR(20) NOT NULL,
    Password VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS Chatroom (
    idChatroom SERIAL PRIMARY KEY,
    name VARCHAR(20) NOT NULL UNIQUE,
    owner INT,
    FOREIGN KEY (owner) REFERENCES Users(idUsers) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS Message (
    idMessage SERIAL PRIMARY KEY,
    author INT,
    room INT,
    text VARCHAR(250),
    date_time TIMESTAMP,
    FOREIGN KEY(author) REFERENCES Users(idUsers) ON DELETE CASCADE,
    FOREIGN KEY(room) REFERENCES Chatroom(idChatroom) ON DELETE CASCADE
);